# Generated by Django 4.2.4 on 2023-08-27 02:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="nickname",
            new_name="username",
        ),
    ]
