# Generated by Django 4.2.4 on 2023-08-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_rename_nickname_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(default=56, max_length=200),
            preserve_default=False,
        ),
    ]
