# Generated by Django 4.2.4 on 2023-08-28 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0003_user_nickname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="username",
            new_name="account",
        ),
    ]
