# Generated by Django 4.2.4 on 2023-08-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0005_user_gender_user_position_user_project_user_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(max_length=32),
        ),
    ]
