# Generated by Django 4.2.4 on 2023-08-29 07:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0007_alter_user_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="user",
            name="position",
        ),
        migrations.RemoveField(
            model_name="user",
            name="project",
        ),
        migrations.RemoveField(
            model_name="user",
            name="scope",
        ),
    ]
