# Generated by Django 4.2.4 on 2023-08-30 01:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_user_gender_user_position_user_project_user_scope_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="account",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="user",
            name="phonenumber",
            field=models.CharField(max_length=32),
        ),
    ]
